### PR TITLE
New constants and functions to  work with the Domoticz built-in security system

### PR DESCRIPTION
**Pull request by ghost**
Added functions to retrieve the state of the Domoticz built-in security system.

Added additional constants used for setting the Domoticz security status, e.g. domoticz.sendCommand('Security Panel', domoticz.SET_SECURITY_ARMAWAY

### CODE REVIEW

**Review by dannybloe — COMMENTED** [review]
Why are these new constants necessary? Are they new?

**Comment by ghost** [comment]
The new constants can be used if You programmatically need to set the state of the Domoticz security device. E.g.
```
domoticz.sendCommand('Security Panel', domoticz.SET_SECURITY_DISARM)
domoticz.sendCommand('Security Panel', domoticz.SET_SECURITY_ARMHOME)
domoticz.sendCommand('Security Panel', domoticz.SET_SECURITY_ARMAWAY)
```

**Comment by ghost** [comment]
The constants are not necessary though. The constants can be declared locally in the current script or you can just hard code the values like this:
```
domoticz.sendCommand('Security Panel', 'Disarm')
domoticz.sendCommand('Security Panel', 'Arm Away')
domoticz.sendCommand('Security Panel', 'Arm Home')
```

**Comment by dannybloe** [comment]
Thing is that there is a contradiction obviously or at least different ways in the code of dealing with this. If you look in the Domoticz code EventSystem.cpp there is no mention at all of 'Arm Away' or 'Arm Home'. It is all 'Arm**ed** Away' and 'Arm**ed** Home'. The only place where it is 'Arm Away' is in RFXNames.cpp. Dunno what kind of device that is but clearly it has its own way of dealing with security.
Just trying to understand stuff here.

So for which commands would you use these other kind of security statuses?

**Comment by ghost** [comment]
The old constants:
```
 		['SECURITY_DISARMED'] = 'Disarmed',
 		['SECURITY_ARMEDAWAY'] = 'Armed Away',
 		['SECURITY_ARMEDHOME'] = 'Armed Home',
```
are needed when _comparing_ the current security panel status. Unfortunately they can not be used for setting the Domoticz security device status though.

Hence the following code will NOT work:
```
domoticz.sendCommand('Security Panel', 'Armed Away')
```


while the following statement should work:
```
domoticz.sendCommand('Security Panel', 'Arm Away')
```

**Comment by dannybloe** [comment]
I'm trying your code to see if I can arm/disarm the security panel at all from Lua but that doesn't seem to work. Are you sure this is possible? As you need to provide the hashed panel code somehow.

**Comment by ghost** [comment]
It works here using Domoticz V3.6371

```
return {
	active = true,
	on = {
		'Test Button',
	},
	execute = function(domoticz, device)
		domoticz.sendCommand('Security Panel', 'Arm Away')
	end
}
```
Just tested it.

After clicking 'Test Button' there is a log entry:
```
2017-05-30 18:09:14.034 (Domoticz Internal) Security (Security Panel)
```

And I can verify the new state by browsing ```http://mydomohost:8080/secpanel/```

**Comment by dannybloe** [comment]
Can you try this with the latest beta (from git preferably)? There's a chance that it is no longer possible to change it from script.

**Comment by ghost** [comment]
OK, I'm currently compiling it and I will let you know the results as soon as possible.

**Comment by ghost** [comment]
Running a clean Domoticz V3.7660 on Ubuntu 16.04 (VirtualBox):

Initially dzVents scripts triggered but then stopped all of a sudden and I  can not make them trigger at all. I can't tell way. Nothing in the logs. 

Anyway, traditional lua scripts trigger and the following scripts can successfully set my Security Device:
```
commandArray = {}
if (devicechanged['Test Button'] == 'On') then
	print('Attempt to arm away')
	commandArray['Security Panel'] = 'Arm Away'
end
if (devicechanged['Test Button'] == 'Off') then
	print('Attempt to disarm')
	commandArray['Security Panel'] = 'Disarm'
end
return commandArray
```
When you run the script, have you checked that the Domoticz Security Device has been "added" in "Devices" and that the name you've chosen for your security device is the same as in the script? (It should appear in devices list after you have set a password)

Cheers!

**Comment by dannybloe** [comment]
Ok, I'll try again.
Oh, and do not use the dzvents stuff that is part of that domoticz checkout. Get the latest from github. The one shipped with dz isn't working at all.

**Comment by dannybloe** [comment]
Aha! The name was the trick!

**Comment by dannybloe** [comment]
So, I added three methods on security devices:
```
mySecurityDevice.armAway()
mySecurityDevice.armHome()
mySecurityDevice.disarm()
```
This will be available soon in the domoticz integration branch. 

I will not merge this PR as it is not needed in this new release. 
Thanks for pointing this out.

**Pull request closed without merging**
